language: generic
sudo: required
services:
    - docker # travis-ci installs docker copy into our running container
before_install:
    - docker build -t atindriyosanyal/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true atindriyosanyal/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-599098477320"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY